CenterDB/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('web.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^dbi/', include('dbi.urls')),
] + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

api/urls.py
from views.asset import *
from rest_framework import renderers
from django.conf.urls import url
from django.conf.urls import include
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
# router.register(r'assets', AssetViewSet)
router.register(r'servers', ServerViewSet)
router.register(r'networkdevices', NetworkDeviceSet)
router.register(r'disks', DiskViewSet)
router.register(r'raids', RaidAdaptorViewSet)
router.register(r'nics', NICViewSet)
router.register(r'memorys', MemoryViewSet)
router.register(r'idcs', IDCViewSet)
router.register(r'businessunits', BusinessUnitViewSet)
router.register(r'perators', OperatorViewSet)
router.register(r'manufactories', ManufactoryViewSet)
router.register(r'tagos', TagViewSet)

urlpatterns = [
    url(r'assets/$', AssetListView.as_view(), name='asset-list'),
    url(r'assets/(?P<pk>[0-9]+)/$', AssetDetailView.as_view(), name='asset-detail'),
    url(r'', include(router.urls)),
]

repository/models.py
#!/usr/bin/env python
# coding: utf-8
from __future__ import unicode_literals

import sys
reload(sys)
sys.setdefaultencoding('utf8')

from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

# Create your models here.


class MyUserManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            username=username,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            password=password,
            username=username,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user

class User(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='邮箱',
        max_length=255,
        unique=True,
    )
    username = models.CharField(verbose_name='用户名', unique=True, max_length=64)
    is_active = models.BooleanField(verbose_name='是否激活', default=True)
    is_admin = models.BooleanField(verbose_name='是否管理员', default=False)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = MyUserManager()

    def get_full_name(self):
        # The user is identified by their email address
        return self.username

    def get_short_name(self):
        # The user is identified by their email address
        return self.username

    def __str__(self):              # __unicode__ on Python 2
        return self.username

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

    class Meta:
        verbose_name_plural = "用户"


class UserGroup(models.Model):
    """
    用户组
    """
    name = models.CharField(max_length=32, unique=True)
    users = models.ManyToManyField('User')

    class Meta:
        verbose_name_plural = "用户组"

    def __str__(self):
        return self.name


class BusinessUnit(models.Model):
    """
    业务线
    """
    name = models.CharField('业务线', max_length=64, unique=True)
    contact = models.ForeignKey('UserGroup', verbose_name='业务联系人', related_name='c', blank=True, null=True)
    manager = models.ForeignKey('UserGroup', verbose_name='系统管理员', related_name='m', blank=True, null=True)

    class Meta:
        verbose_name_plural = "业务线"

    def __str__(self):
        return self.name


class Operator(models.Model):
    """
    运营商表   例如：电信 联通 教育网 长城宽带等
    被机房关联。本身不关联任何表 只记录
    """
    name = models.CharField('运营商', max_length=64, unique=True)
    memo = models.CharField('备注', max_length=128, blank=True,null=True)

    class Meta:
        verbose_name = '运营商'
        verbose_name_plural = "运营商"

    def __str__(self):
        return self.name


class IDC(models.Model):
    """
    机房表结构 关联合同和运营商
    机房表需要机房联系人 联系电话 机房的基本信息等
    """
    name = models.CharField(u'机房名称', max_length=64, unique=True)
    contacts = models.CharField('机房技术', max_length=63, null=True, blank=True)
    idc_phone = models.IntegerField('机房电话', null=True, blank=True)
    contacts_phone = models.IntegerField('联系人电话', null=True, blank=True)
    contacts_qq = models.IntegerField('机房技术QQ', null=True, blank=True)
    idc_addr = models.CharField('机房地址', max_length=63, null=True, blank=True)
    bandwidth = models.CharField('机房带宽', max_length=63, null=True, blank=True)
    operator = models.ForeignKey('Operator', verbose_name=u'运营商', null=True, blank=True)
    memo = models.CharField(u'备注', max_length=128, blank=True, null=True)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name = '机房'
        verbose_name_plural = "机房"


class Tag(models.Model):
    """
    资产标签
    """
    name = models.CharField('标签', max_length=32, unique=True)

    class Meta:
        verbose_name_plural = "标签"

    def __str__(self):
        return self.name


class Asset(models.Model):
    """
    资产信息表，所有资产公共信息（交换机，服务器，防火墙等）
    """
    asset_type_choices = (
        ('physical_host', '物理机'),
        ('virtual_host', '虚拟机'),
        ('cloud_host', '云主机'),
        ('switch', '交换机'),
        ('router', '路由器'),
        ('firewall', '防火墙'),
        ('storage', '防火墙'),
        ('others', '其他'),
    )
    asset_status_choices = (
        ('on', '上架'),
        ('on_line', '在线'),
        ('off_line', '离线'),
        ('off', '下架'),
    )

    device_type = models.CharField(verbose_name='资产类型', choices=asset_type_choices, max_length=64, default='virtual_host')
    device_status = models.CharField(verbose_name='资产状态', choices=asset_status_choices, max_length=64, default='on')
    name = models.CharField(verbose_name='资产名称', max_length=64, blank=True, null=True, unique=True)
    sn = models.CharField('资产SN号', max_length=128, null=True, blank=True)
    uuid = models.CharField('UUID', max_length=64, unique=True, null=True)
    manufactory = models.ForeignKey('Manufactory', verbose_name=u'制造商', null=True, blank=True)
    cabinet_num = models.CharField('机柜号', max_length=30, null=True, blank=True)
    cabinet_order = models.CharField('机柜中序号', max_length=30, null=True, blank=True)
    idc = models.ForeignKey('IDC', verbose_name='IDC机房', null=True, blank=True)
    business_unit = models.ForeignKey('BusinessUnit', verbose_name='属于的业务线', null=True, blank=True)
    tag = models.ManyToManyField('Tag', blank=True)
    memo = models.TextField('备注', null=True, blank=True)
    update_date = models.DateField(auto_now=True)
    create_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "资产"

    # def __str__(self):
    #     return str(self.name)


class Server(models.Model):
    """
    服务器信息
    """

    asset = models.OneToOneField('Asset', related_name='server')

    hosted_on = models.ForeignKey('self', related_name='hosted_on_server', blank=True, null=True)
    hostname = models.CharField(max_length=128)
    manufacturer = models.CharField(verbose_name='制造商', max_length=64, null=True, blank=True)
    model = models.CharField('型号', max_length=64, null=True, blank=True)

    manage_ip = models.GenericIPAddressField('管理IP', null=True, blank=True)

    kernel_release = models.CharField(u'内核', max_length=128, null=True, blank=True)
    os_platform = models.CharField('系统', max_length=16, null=True, blank=True)
    os_version = models.CharField('系统版本', max_length=16, null=True, blank=True)

    cpu_count = models.IntegerField('CPU个数', null=True, blank=True)
    cpu_physical_count = models.IntegerField('CPU物理个数', null=True, blank=True)
    cpu_model = models.CharField('CPU型号', max_length=128, null=True, blank=True)

    memo = models.TextField('备注', null=True, blank=True)
    update_date = models.DateTimeField('更新日期', auto_now=True, blank=True)
    create_date = models.DateTimeField('添加日期', auto_now_add=True, blank=True)

    class Meta:
        verbose_name_plural = "服务器"

    def __str__(self):
        return self.hostname


class NetworkDevice(models.Model):
    asset = models.OneToOneField('Asset')
    management_ip = models.CharField('管理IP', max_length=64, blank=True, null=True)
    vlan_ip = models.CharField('VlanIP', max_length=64, blank=True, null=True)
    intranet_ip = models.CharField('内网IP', max_length=128, blank=True, null=True)
    sn = models.CharField('SN号', max_length=64, unique=True)
    manufacture = models.ForeignKey('Manufactory', verbose_name=u'制造商', max_length=128, null=True, blank=True)
    model = models.CharField('型号', max_length=128, null=True, blank=True)
    port_num = models.SmallIntegerField('端口个数', null=True, blank=True)
    device_detail = models.CharField('设置详细配置', max_length=255, null=True, blank=True)

    memo = models.TextField('备注', null=True, blank=True)
    update_date = models.DateTimeField('更新日期', auto_now=True, blank=True)
    create_date = models.DateTimeField('添加日期', auto_now_add=True, blank=True)

    class Meta:
        verbose_name_plural = "网络设备"

    def __str__(self):
        return self.vlan_ip


class Disk(models.Model):
    """
    硬盘信息
    """
    disk_type_choice = (
        ('SATA', 'SATA'),
        ('SAS', 'SAS'),
        ('SCSI', 'SCSI'),
        ('SSD', 'SSD'),
    )
    asset = models.ForeignKey('Asset', related_name='disk')
    slot = models.CharField('插槽位', max_length=8)
    model = models.CharField('磁盘型号', max_length=32)
    manufactory = models.CharField(u'制造商', max_length=64, blank=True, null=True)
    capacity = models.FloatField('磁盘容量GB')
    disk_type = models.CharField('磁盘类型', choices=disk_type_choice, max_length=32, default='SATA')
    memo = models.TextField('备注', null=True, blank=True)
    update_date = models.DateTimeField('更新日期', auto_now=True, blank=True)
    create_date = models.DateTimeField('添加日期', auto_now_add=True, blank=True)

    class Meta:
        verbose_name_plural = "硬盘"

    def __str__(self):
        return '%s:%s:%s' % (self.asset_id, self.slot, self.capacity)


class RaidAdaptor(models.Model):
    """
    raid卡
    """
    asset = models.ForeignKey('Asset')
    sn = models.CharField(u'SN号', max_length=128, blank=True, null=True)
    slot = models.CharField(u'插口', max_length=64)
    model = models.CharField(u'型号', max_length=64, blank=True, null=True)

api/views/asset.py
from rest_framework import viewsets
from rest_framework.views import APIView
from rest_framework import mixins
from rest_framework import generics
from rest_framework.decorators import detail_route, list_route
from rest_framework.response import Response
from rest_framework import status
from repository.models import *
from ..serializers.asset import *
from importlib import import_module


# class AssetViewSet(viewsets.ModelViewSet):
#     queryset = Asset.objects.all()
#     serializer_class = AssetSerializer
#     lookup_field = 'manufactory'

class AssetListView(APIView):
    def get_object_id(self, data, model_name, object_name):
        mod = import_module('repository.models')
        model_obj = getattr(mod, model_name)
        if isinstance(data.get(object_name, None), dict):
            obj_dict = data.pop(object_name)
            obj, _ = model_obj.objects.get_or_create(name=obj_dict['name'])
            data.update({object_name: obj.id})

    def get(self, request, format=None):
        assets = Asset.objects.all()
        serializer = AssetSerializer(assets, many=True)
        return Response(serializer.data)

    def post(self, request, format=None):
        data = request.data
        self.get_object_id(data, 'Manufactory', 'manufactory')
        self.get_object_id(data, 'IDC', 'idc')
        self.get_object_id(data, 'BusinessUnit', 'business_unit')
        serializer = AssetSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

class AssetDetailView(APIView):
    def get_object(self, pk):
        try:
            return Asset.objects.get(pk=pk)
        except Asset.DoesNotExist:
            return Http404

    def get(self, request, pk, format=None):
        asset = self.get_object(pk)
        serializer = AssetSerializer(asset)
        return Response(serializer.data)

    def put(self, request, pk, format=None):
        asset = self.get_object(pk)
        serializer = AssetSerializer(asset, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def patch(self, request, format=None):
        asset = self.get_object(pk)
        serializer = AssetSerializer(asset, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


    def delete(self, request, pk, format=None):
        asset = self.get_object(pk)
        asset.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


class ServerViewSet(viewsets.ModelViewSet):
    queryset = Server.objects.all()
    serializer_class = ServerSerializer


class DiskViewSet(viewsets.ModelViewSet):
    queryset = Disk.objects.all()
    serializer_class = DiskSerializer



class RaidAdaptorViewSet(viewsets.ModelViewSet):
    queryset = RaidAdaptor.objects.all()
    serializer_class = RaidAdaptorSerializer


class NetworkDeviceSet(viewsets.ModelViewSet):
    queryset = NetworkDevice.objects.all()
    serializer_class = NetworkDeviceSerializer


class NICViewSet(viewsets.ModelViewSet):
    queryset = Disk.objects.all()
    serializer_class = NICSerializer


class MemoryViewSet(viewsets.ModelViewSet):
    queryset = Memory.objects.all()
    serializer_class = MemorySerializer


class IDCViewSet(viewsets.ModelViewSet):
    queryset = IDC.objects.all()
    serializer_class = MemorySerializer


class BusinessUnitViewSet(viewsets.ModelViewSet):
    queryset = BusinessUnit.objects.all()
    serializer_class = MemorySerializer


class OperatorViewSet(viewsets.ModelViewSet):
    queryset = Operator.objects.all()
    serializer_class = MemorySerializer


class TagViewSet(viewsets.ModelViewSet):
    queryset = Tag.objects.all()
    serializer_class = TagSerializer


class ManufactoryViewSet(viewsets.ModelViewSet):
    queryset = Manufactory.objects.all()
    serializer_class = ManufactorySerializer
    lookup_field = 'manufactory'
    lookup_url_kwarg = 'manufactory'


# class ManufactoryDetailView(mixins.CreateModelMixin,
#                             mixins.RetrieveModelMixin,
#                             mixins.DestroyModelMixin,
#                             generics.GenericAPIView)
#
#     queryset = Manufactory.objects.all()
#     serializer_class = ManufactorySerializer
#
#     lookup_field = manufactory
#
#     def get(self, request, *args, **kwargs):
#         return self.get(request, *args, **kwargs)
#
#     def put(self,  request, *args, **kwargs):
#         return self.put(request, *args, **kwargs)
#
#     def delete(self, request, *args, **kwargs):
#         return self.delete(request, *args, **kwargs)




class AssetRecordViewSet(viewsets.ModelViewSet):
    queryset = Manufactory.objects.all()
    serializer_class = TagSerializer


class ErrorLogViewSet(viewsets.ModelViewSet):
    queryset = Manufactory.objects.all()
    serializer_class = TagSerializer

web/templates/assets/asset_detail.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap3 %}
{% load i18n %}


{% block body %}
    <div id="wrapper">

    {% include 'navbar.html' %}
        <div id="page-wrapper" style="min-height: 368px;">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">资产详情</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            详情列表
                        </div>

                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-hover">
                                    <thead>
                                        <tr>
                                            <th>资产项</th>
                                            <th>项目信息</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>类型</td>
                                            <td>{{ asset.get_device_type_display }}</td>
                                        </tr>
                                        <tr>
                                            <td>状态</td>
                                            <td>{{ asset.get_device_status_display}}</td>
                                        </tr>
                                        <tr>
                                            <td>SN</td>
                                            <td>{{ asset.sn}}</td>
                                        </tr>
                                        <tr>
                                            <td>厂家</td>
                                            <td>{{ asset.manufactory}}</td>
                                        </tr>
                                        <tr>
                                            <td>机柜号</td>
                                            <td>{{ asset.cabinet_num}}</td>
                                        </tr>
                                        <tr>
                                            <td>机柜位置</td>
                                            <td>{{ asset.cabinet_order}}</td>
                                        </tr>
                                        <tr>
                                            <td>IDC</td>
                                            <td>{{ asset.idc}}</td>
                                        </tr>
                                        <tr>
                                            <td>业务线</td>
                                            <td>{{ asset.business_unit}}</td>
                                        </tr>
                                        <tr>
                                            <td>标签</td>
                                            <td>{{ asset.tag}}</td>
                                        </tr>
                                        <tr>
                                            <td>备注</td>
                                            <td>{{ asset.memo}}</td>
                                        </tr>
                                    </tbody>

                            </div>
                            <!-- /.table-responsive -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
            </div>

        </div>


    </div>



{% endblock %}

web/templates/assets/asset_list.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap3 %}
{% load i18n %}


{% block body %}
    <div id="wrapper">

    {% include 'navbar.html' %}
        <div id="page-wrapper" style="min-height: 368px;">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">资产列表</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            DataTables Advanced Tables
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer"><div class="row"><div class="col-sm-6"><div class="dataTables_length" id="dataTables-example_length"><label>Show <select name="dataTables-example_length" aria-controls="dataTables-example" class="form-control input-sm"><option value="10">10</option><option value="25">25</option><option value="50">50</option><option value="100">100</option></select> entries</label></div></div><div class="col-sm-6"><div id="dataTables-example_filter" class="dataTables_filter"><label>Search:<input type="search" class="form-control input-sm" placeholder="" aria-controls="dataTables-example"></label></div></div></div><div class="row"><div class="col-sm-12"><table width="100%" class="table table-striped table-bordered table-hover dataTable no-footer dtr-inline" id="dataTables-example" role="grid" aria-describedby="dataTables-example_info" style="width: 100%;">
                                <thead>
                                    <tr role="row">
                                        <th class="sorting_asc" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column descending" style="width: 185px;" aria-sort="ascending">资产类型</th>
                                        <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending" style="width: 224px;">资产状态</th>
                                        <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending" style="width: 206px;">IDC</th>
                                        <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending" style="width: 161px;">制造商</th>
                                        <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending" style="width: 121px;">SN</th>
                                        <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending" style="width: 121px;">操作</th>
                                    </tr>
                                </thead>
                                <tbody>

                                    {% for asset in asset_list %}
                                    <tr class="gradeA odd" role="row">

                                        <td class="sorting_1"><a href="{% url 'asset_detail' asset.id %}"> {{ asset.get_device_type_display }}</a></td>
                                        <td>{{ asset.get_device_status_display }}</td>
                                        <td>{{ asset.idc }}</td>
                                        <td class="center">{{ asset.manufactory }}</td>
                                        <td class="center">{{ asset.sn }}</td>
                                        <td class="center"><a href={% url 'asset_update'  asset.id %}>更新</a>&nbsp;&nbsp;&nbsp;<a href={% url 'asset_delete'  asset.id %}>删除</a></td>

                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="dataTables_info" id="dataTables-example_info" role="status" aria-live="polite">Showing 1 to 10 of {{ page_obj.paginator.num_pages }} entries</div>
                            </div>
                            <div class="col-sm-6">
                                <div class="dataTables_paginate paging_simple_numbers" id="dataTables-example_paginate">
                                    <ul class="pagination">
                                        <li><a href="{{ request.path }}?page=1">首页</a></li>
                                        {% if page_obj.has_previous %}
                                        <li class="paginate_button previous " aria-controls="dataTables-example" tabindex="0" id="dataTables-example_previous">
                                            <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">Previous</a>
                                        </li>
                                        {% endif %}

                                        {% for pg in page_obj.paginator.page_range %}
                                            {% if page_obj.number == pg %}
                                            <li class="paginate_button active" aria-controls="dataTables-example" tabindex="0">
                                                <a href="?page={{pg}}">{{pg}}</a>
                                            </li>
                                            {% else %}
                                            <li class="paginate_button " aria-controls="dataTables-example" tabindex="0">
                                                <a href="?page={{pg}}">{{pg}}</a>
                                            </li>
                                            {% endif %}
                                        {% endfor %}

                                        {% if page_obj.has_next %}
                                        <li class="paginate_button next" aria-controls="dataTables-example" tabindex="0" id="dataTables-example_next">
                                            <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">Next</a>
                                        </li>
                                        {% endif %}
                                        <li><a href="{{ request.path }}?page={{ page_obj.paginator.num_pages }}">尾页</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                </div>
                            <!-- /.table-responsive -->

                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>

        </div>
    <div>

</div>

    </div>

{% endblock %}

web/templates/assets/delete_confirm.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>删除确认</title>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}
    <p>是否确认删除 <b>{{ object.sn }} </b> ?</p>
    <input type="submit" value="确认" />
</form>
</body>
</html>

web/templates/assets/disk_create.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap3 %}
{% load i18n %}


{% block body %}
    <div id="wrapper">

    {% include 'navbar.html' %}

        <div id="page-wrapper" style="min-height: 368px;">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">服务器创建</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            服务器表单
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-lg-6">

                                    <form role="form" action="" method="post" >
                                        {% csrf_token %}
                                        <div class="form-group">
                                            {% bootstrap_field form.asset  %}
                                        </div>
                                        <div class="form-group">
                                            {% bootstrap_field form.slot  %}
                                        </div>
                                        <div class="form-group">
                                            {% bootstrap_field form.model  %}
                                        </div>
                                        <div class="form-group">
                                            {% bootstrap_field form.manufactory  %}
                                        </div>
                                        <div class="form-group">
                                            {% bootstrap_field form.capacity  %}
                                        </div>
                                        <div class="form-group">
                                            {% bootstrap_field form.disk_type  %}
                                        </div>
                                        <div class="form-group">
                                            {% bootstrap_field form.memo  %}
                                        </div>

                                        <button type="submit" class="btn btn-default">提交</button>
                                    </form>
                                </div>


                                </div>
                                <!-- /.col-lg-6 (nested) -->
                            </div>
                            <!-- /.row (nested) -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->



{% endblock %}